version: '3.9'
services:
  api:
    image: python:3.11-slim
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - S3_BUCKET=${S3_BUCKET}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
    volumes:
      - ./:/app
    # depends_on:
    #   - redis
    #   - db

  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"

  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: app
  #     POSTGRES_USER: app
  #     POSTGRES_PASSWORD: app
  #   ports:
  #     - "5432:5432"
